name: Build and Deploy .NET API to Azure

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: |
          cd server
          dotnet restore

      - name: Build
        run: |
          cd server
          dotnet build --configuration Release

      - name: Publish .NET Core app
        run: |
          cd server
          dotnet publish -c Release -o publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E8EB00EAE0434B27A2A1916F27F06C77 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E5A309FCA73446808C4AA9298FC0E9A0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EF4BFF33EF524EAE8117CC0CCAE7D83C }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "unhurd-tech-test-api"
          slot-name: "Production"
          package: ./server/publish
