name: Build and deploy ASP.Net Core app to Azure Web App - unhurd-tech-test-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Change directory to server folder
        run: cd server # Change to the 'server' directory

      - name: List contents of 'server' directory (debugging)
        run: dir ./ # List contents of the 'server' folder to make sure the .csproj exists

      - name: Build with dotnet
        run: dotnet build --configuration Release # Build in the 'server' folder

      - name: List contents after build (debugging)
        run: dir ./bin/Release/net8.0 # List contents of build output folder to confirm it's being built

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{ github.workspace }}/publish # Publish to the workspace publish folder

      - name: List contents after publish (debugging)
        run: dir ${{ github.workspace }}/publish # List the contents of the published output

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/publish # Upload from the publish directory

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: List downloaded artifact contents
        run: |
          echo "Listing contents of downloaded artifact:"
          dir ${{ github.workspace }}/publish  # Verify the contents of the artifact

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E8EB00EAE0434B27A2A1916F27F06C77 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E5A309FCA73446808C4AA9298FC0E9A0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EF4BFF33EF524EAE8117CC0CCAE7D83C }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "unhurd-tech-test-api"
          slot-name: "Production"
          package: ${{ github.workspace }}/publish # Package from the correct publish directory
