name: Build and deploy ASP.Net Core app to Azure Web App - unhurd-tech-test-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Build and Publish
        run: |
          cd server
          dotnet build --configuration Release
          dotnet publish -c Release -o ${{ github.workspace }}/publish

      - name: List contents after publish (debugging)
        run: dir ${{ github.workspace }}/publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E8EB00EAE0434B27A2A1916F27F06C77 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E5A309FCA73446808C4AA9298FC0E9A0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EF4BFF33EF524EAE8117CC0CCAE7D83C }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "unhurd-tech-test-api"
          slot-name: "Production"
          package: ${{ github.workspace }}/publish
